import 'package:flutter/material.dart';
import 'package:aouikit/aouikit.dart';

final brandColors = AoUiColors(
  primary: const Color(0xFF0057B8),
  onPrimary: Colors.white,
  primaryContainer: const Color(0xFFB3D1F6),
  onPrimaryContainer: Colors.black,
  secondary: const Color(0xFFFFB300),
  onSecondary: Colors.black,
  secondaryContainer: const Color(0xFFFFE082),
  onSecondaryContainer: Colors.black,
  tertiary: const Color(0xFF43A047),
  onTertiary: Colors.white,
  tertiaryContainer: const Color(0xFFC8E6C9),
  onTertiaryContainer: Colors.black,
  error: const Color(0xFFD32F2F),
  onError: Colors.white,
  errorContainer: const Color(0xFFFFCDD2),
  onErrorContainer: Colors.black,
  surface: Colors.white,
  onSurface: Colors.black,
  surfaceContainerLowest: const Color(0xFFF5F5F5),
  surfaceContainerLow: const Color(0xFFE0E0E0),
  surfaceContainer: const Color(0xFFEEEEEE),
  surfaceContainerHigh: const Color(0xFFE0E0E0),
  surfaceContainerHighest: const Color(0xFFBDBDBD),
  outline: const Color(0xFF90A4AE),
  outlineVariant: const Color(0xFFB0BEC5),
  shadow: Colors.black26,
  scrim: Colors.black38,
  inverseSurface: const Color(0xFF212121),
  inversePrimary: const Color(0xFF1976D2),
  disabledBackground: const Color(0xFFE0E0E0),
  disabledContent: const Color(0xFF9E9E9E),
  link: const Color(0xFF1E88E5),
  success: const Color(0xFF4CAF50),
  warning: const Color(0xFFFFC107),
  info: const Color(0xFF2196F3),
);
